server:
  port: 28081
dubbo:
  application:
    name: tx-tcc-consumer
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://127.0.0.1:8848
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
