spring:
  datasource:
    dynamic:
      primary: order0
      datasource:
        order0:
          url: jdbc:mysql://rm-2zen1c7k0onnvs8zbyo.mysql.rds.aliyuncs.com:3306/order_db0?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
          driver-class-name: com.mysql.jdbc.Driver
          username: lhj502819
          password: 960706Chh!
        order1:
          url: jdbc:mysql://rm-2zen1c7k0onnvs8zbyo.mysql.rds.aliyuncs.com:3306/order_db1?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
          driver-class-name: com.mysql.jdbc.Driver
          username: lhj502819
          password: 960706Chh!

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: cn.iocoder.springboot.lab17.dynamicdatasource.dataobject # 配置数据库实体包路径