spring:
  datasource:
    order-master:
      url: jdbc:mysql://rm-2zen1c7k0onnvs8zbyo.mysql.rds.aliyuncs.com:3306/order_db0?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.jdbc.Driver
      username: lhj502819
      password: 960706Chh!
    order-slave:
      url: jdbc:mysql://rm-2zen1c7k0onnvs8zbyo.mysql.rds.aliyuncs.com:3306/order_db1?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.jdbc.Driver
      username: lhj502819
      password: 960706Chh!