 CREATE TABLE `t_order0` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order1` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order2` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order3` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order4` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order5` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order6` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order7` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order8` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order9` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order10` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order11` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order12` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order13` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order14` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t_order15` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `order_no` VARBINARY(64) NOT NULL COMMENT '订单号',
  `product_id` BIGINT(11) NOT NULL COMMENT '商品id',
  `product_name` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL COMMENT '商品名称',
  `product_image` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL COMMENT '商品图片',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `origin_price` INT(11) NOT NULL COMMENT '原始单价，单位：分',
  `buy_price` INT(11) NOT NULL COMMENT '购买单价，单位：分',
  `payment_time` DATETIME NOT NULL COMMENT '付款时间',
  `delivery_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receiver_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `user_id` BIGINT(11) NOT NULL COMMENT '用户id',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态：0、代发货 1、已发货 2、已收货 20、换货中 21、换货成功 40、退货中 41、已退货',
  `deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除状态',
  PRIMARY KEY (`id`),
  KEY `USER_ID_INDEX` (`user_id`),
  KEY `USER_PRODUCT_NAME_INDEX` (`user_id`,`product_name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

