server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://lhj502819.mysql.rds.aliyuncs.com:3306/db0?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: lhj502819
    password: 960706Chh!
    hikari:
      readOnly: false
      connectionTimeout: 30000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 120000
      loginTimeout: 5
      maximumPoolSize: 10
      minimumIdle: 10
      connection-test-query: select 1
dubbo:
  application:
    name: account-userA
    qos-enable: false
    qos-accept-foreign-ip: false
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://127.0.0.1:8848
nacos:
  discovery:
    server-addr: 127.0.0.1:8848


# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: INFO
    foreignexchange:
      account:
        userA:
          mapper: debug

